clean:
    rm  -rf *.o
    rm  -rf *.a
    rm  -rf mainsloop
    rm  -rf mains
    rm  -rf maindloop
    rm  -rf maindrec

main.o: main.c numClass.h
    gcc -c main.c -o main.o

basicClassification.o: basicClassification.c numClass.h
    gcc -c basicClassification.c -o basicClassification.o

advancedClassificationLoop.o: advancedClassificationLoop.c numClass.h
    gcc -c advancedClassificationLoop.c -o advancedClassificationLoop.o


advancedClassificationRecursion.o: advancedClassificationRecursion.c numClass.h
    gcc -c advancedClassificationRecursion.c -o advancedClassificationRecursion.o

//static//

libclassloops.a: advancedClassificationLoop.o basicClassification.o
    ar -rc libclassloops.a advancedClassificationLoop.o basicClassification.o

mainsloop: main.o libclassloops.a
    gcc -o mainsloop main.o -L. libclassloops.a

libclassrec.a: advancedClassificationRecursion.o basicClassification.o
    ar -rc libclassrec.a advancedClassificationRecursion.o basicClassification.o

mains: main.o libclassrec.a
    gcc -o mains main.o -L. libclassrec.a
//dynamic//

basicClassificationPIC.o: basicClassification.c numClass.h
    gcc -fpic -c basicClassification.c -o basicClassificationPIC.o

advancedClassificationLoopPIC.o: advancedClassificationLoop.c numClass.h
    gcc -fpic -c advancedClassificationLoop.c -o advancedClassificationLoopPIC.o

advancedClassificationRecursionPIC.o: advancedClassificationRecursion.c numClass.h
    gcc -c -fpic advancedClassificationRecursion.c -o advancedClassificationRecursionPIC.o

libclassloops.so: basicClassificationPIC.o advancedClassificationLoopPIC.o
    gcc -shared -o libclassloops.so basicClassificationPIC.o advancedClassificationLoopPIC.o

maindloop: main.o libclassloops.so
    gcc -o maindloop main.o ./libclassloops.so

libclassrec.so:  basicClassificationPIC.o advancedClassificationRecursionPIC.o
    gcc -shared basicClassificationPIC.o advancedClassificationRecursionPIC.o -o libclassrec.so

maindrec: main.o libclassrec.so
    gcc -o maindrec main.o ./libclassrec.so

	
